[lint]
select = ["E4", "E7", "E9", "F", "I", "B008"]
ignore = ["E501", "F401"]

[lint.per-file-ignores]
"tests/**/*.py" = ["E402"]

[lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.File"]
