"""Layout metrics for the responsive desktop application shell."""

from .tokens import MIN_WINDOW_HEIGHT, MIN_WINDOW_WIDTH, SIDEBAR_WIDTH, TOPBAR_HEIGHT

SIDEBAR_COLLAPSED_WIDTH = 60
STATUSBAR_HEIGHT = 28
CONTENT_MAX_WIDTH = 1600
PAGE_MARGIN = 24
PAGE_MARGIN_NARROW = 16
DETAIL_INSPECTOR_WIDTH = 320
